### ISSUE TITLE
Can you make this repo a template?

### ISSUE THREAD

**Issue by blopa** [josephmbustamante/phaser3-typescript-starter-kit#15]
Hey. I would like to use your repo as a base for a template that I want to use in my game, and if you make this a template, my repo will have a `generated from josephmbustamante/phaser3-typescript-starter-kit` and people will know where most of the code came from.

I rather do that than simply copying and pasting your code into my own repo.

Thanks

**Comment by josephmbustamante** [comment]
Thanks for mentioning that - I didn't realize GitHub had added templates. Just changed it over so you should be able to use it as a template for a new repo!
