### ISSUE TITLE
yarn install does not work with node 16.0.0-head

### ISSUE THREAD

**Issue by elsni** [josephmbustamante/phaser3-typescript-starter-kit#16]
I try to yarn install on node 16.0.0-head. I have to use this version because it is the first one that runs yarn without errors natively on M1 mac.

Output:

`yarn install v1.22.10
warning You are using Node "16.0.0-head" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
[1/4] 🔍  Resolving packages...

[2/4] 🚚  Fetching packages...

error exports-loader@1.1.1: The engine "node" is incompatible with this module. Expected version ">= 10.13.0". Got "16.0.0-head"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**Comment by josephmbustamante** [comment]
I'm not able to recreate this issue on my own - is this still a problem/anyone else having trouble installing dependencies?

**Comment by josephmbustamante** [comment]
Closing this for now - if anyone still has trouble getting the install to work please feel free to open a new issue!
