### ISSUE TITLE
Cannot find module 

### ISSUE THREAD

**Issue by atlantageek** [josephmbustamante/phaser3-typescript-starter-kit#23]
Getting the following error

$ webpack --mode development && webpack serve --mode development
[webpack-cli] Failed to load '/home/atlantageek/dev/phasergames/phaser3-typescript/src/boilerplates/webpack-boilerplate/webpack.config.js' config
[webpack-cli] Error: Cannot find module 'Phaser'
Require stack:
- /home/atlantageek/dev/phasergames/phaser3-typescript/src/boilerplates/webpack-boilerplate/webpack.config.js

**Comment by guanglinwei** [comment]
Did you find a solution to this? I'm having the same problem.
